name: Docker_build_push

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.15, 18.16.0, 18.16.1]
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Patch downloader.js
        run: cp downloader.js node_modules/hardhat/internal/solidity/compiler/downloader.js

      - name: Patch download.js
        run: cp download.js node_modules/hardhat/internal/util/download.js

      - name: Run tests
        run: npx hardhat test --verbose
